[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django-ckeditor-5>=0.2.18",
    "django>=5.2.6",
    "gunicorn>=23.0.0",
    "pillow>=11.3.0",
    "whitenoise>=6.10.0",
]
