# Generated by Django 5.2.6 on 2025-09-11 18:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_course_syllabus_course_estimated_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', django_ckeditor_5.fields.CKEditor5Field(help_text="Academy's vision statement")),
                ('mission', django_ckeditor_5.fields.CKEditor5Field(help_text="Academy's mission statement")),
                ('values', django_ckeditor_5.fields.CKEditor5Field(help_text='Core values and principles')),
                ('story', django_ckeditor_5.fields.CKEditor5Field(help_text='Journey and credibility of LUM Data Academy')),
                ('partners', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Partners and collaborators information')),
                ('hero_title', models.CharField(default='About LUM Data Academy', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='Equipping Africa with Future-Ready Data Skills', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Main blog post content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Brief excerpt or summary (max 300 characters)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Event description and details'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Testimonial content'),
        ),
    ]
