# Generated by Django 5.2.6 on 2025-09-12 21:18

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enrollment_paymentinstallment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('department', models.CharField(help_text='e.g., Academic, Technology, Administration', max_length=100)),
                ('location', models.CharField(help_text='e.g., Nairobi, Remote, Hybrid', max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=50)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed job description')),
                ('responsibilities', django_ckeditor_5.fields.CKEditor5Field(help_text='Key responsibilities')),
                ('requirements', django_ckeditor_5.fields.CKEditor5Field(help_text='Required qualifications and skills')),
                ('benefits', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Benefits and perks')),
                ('salary_range', models.CharField(blank=True, help_text='e.g., KShs 50,000 - 80,000', max_length=100)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(default='careers@lumdataacademy.org', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Opportunity',
                'verbose_name_plural': 'Career Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Survey description and purpose')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Survey questions and content')),
                ('survey_type', models.CharField(choices=[('course_feedback', 'Course Feedback'), ('general_feedback', 'General Feedback'), ('market_research', 'Market Research'), ('student_satisfaction', 'Student Satisfaction'), ('other', 'Other')], default='general_feedback', max_length=50)),
                ('target_audience', models.CharField(blank=True, help_text='e.g., Students, Alumni, General Public', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=True, help_text='Allow anonymous responses')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_responses', models.PositiveIntegerField(blank=True, help_text='Maximum number of responses', null=True)),
                ('response_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
