# Generated by Django 5.2.6 on 2025-09-14 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_completions', to='courses.enrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.coursemodule')),
            ],
            options={
                'db_table': 'core_modulecompletion',
                'ordering': ['-completed_at'],
                'unique_together': {('enrollment', 'module')},
            },
        ),
        migrations.CreateModel(
            name='ProjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submission_notes', models.TextField(blank=True, help_text="Student's submission notes")),
                ('instructor_feedback', models.TextField(blank=True, help_text='Instructor feedback')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Grade out of 100', max_digits=5, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_enrollments', to='courses.enrollment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.capstoneproject')),
            ],
            options={
                'db_table': 'core_projectenrollment',
                'ordering': ['-started_at'],
                'unique_together': {('enrollment', 'project')},
            },
        ),
    ]
