# Generated by Django 5.2.6 on 2025-09-15 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_instructor_course_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenrollment',
            name='additional_links',
            field=models.TextField(blank=True, help_text='Any additional project links (one per line)'),
        ),
        migrations.AddField(
            model_name='projectenrollment',
            name='certificate_download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectenrollment',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='projectenrollment',
            name='certificate_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectenrollment',
            name='github_repo_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL'),
        ),
        migrations.AddField(
            model_name='projectenrollment',
            name='google_colab_url',
            field=models.URLField(blank=True, help_text='Google Colab notebook URL'),
        ),
        migrations.AddField(
            model_name='projectenrollment',
            name='jupyter_notebook_url',
            field=models.URLField(blank=True, help_text='Jupyter Notebook URL or file link'),
        ),
        migrations.AddField(
            model_name='projectenrollment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectenrollment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
